import argparse
import re
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from harness_shared import (
    get_field_value,
    get_section_text,
    get_task_number,
    get_task_status,
    find_repo_root,
    find_harness_root,
    die,
)


def _read_text(path):
    try:
        return path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return path.read_text(encoding="latin-1")


def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--RecentTasks", type=int, default=4)
    p.add_argument("--RecentReviews", type=int, default=4)
    p.add_argument("--RecentReceipts", type=int, default=4)
    p.add_argument("--TaskStream", default="")
    return p.parse_args()


def get_section_first_line(content, heading):
    text = get_section_text(content, heading)
    if not text:
        return ""
    for line in text.splitlines():
        stripped = line.strip()
        if stripped:
            return stripped
    return ""


def read_task_summary(file_path):
    content = _read_text(file_path)
    return {
        "number": get_task_number(file_path),
        "name": file_path.name,
        "status": get_task_status(content),
        "stream": get_field_value(content, "Task Stream"),
        "goal": get_section_first_line(content, "Goal"),
        "generated": "yes" if "Generated by: scripts/new_task_brief.py" in content else "no",
    }


def read_review_summary(file_path):
    content = _read_text(file_path)
    return {
        "number": get_task_number(file_path),
        "name": file_path.name,
        "verdict": get_section_first_line(content, "Verdict"),
        "generated": "yes" if "Generated by: scripts/new_review_draft.py" in content else "no",
    }


def get_recent_files(path, count):
    if not path.exists():
        return []
    files = sorted(
        [f for f in path.iterdir() if f.is_file() and f.suffix == ".md"],
        key=lambda f: f.name,
        reverse=True,
    )
    return files[:count]


def main():
    args = parse_args()
    root = find_repo_root()
    harness_root = find_harness_root()

    output = []

    output.append("HARNESS_CONTEXT_SUMMARY")
    output.append("Purpose: token-bounded context entrypoint. Prefer this summary over broad Glob/Grep/Read across task-briefs, reviews, execution-receipts, or all .dev-harness markdown.")
    output.append("")
    output.append("Generator-first tools:")
    output.append("- task brief: harness-engine/.dev-harness/scripts/new_task_brief.py")
    output.append("- long task brief input: write a bounded JSON spec file, then run new_task_brief.py --SpecFile <path>")
    output.append("- SpecFile must contain Title, TaskStream, RunType, Layer, RiskClass, Intent, and Goal before invoking the generator.")
    output.append("- review draft: harness-engine/.dev-harness/scripts/new_review_draft.py")
    output.append("- review draft short input: run new_review_draft.py --Task <NNN> instead of guessing the full task path")
    output.append("- scope check: harness-engine/.dev-harness/checks/scope_diff_gate.py")
    output.append("")
    output.append("Repo-root command rules:")
    output.append(f"- repo root: {root}")
    output.append("- Run harness scripts/checks from repo root or by repo-root absolute path; never run harness generators from inside cockpit-api.")
    output.append("- Before Read on any guessed/generated path, verify file exists before Read with a bounded listing or Test-Path equivalent.")
    output.append("- If `cd cockpit-api` fails once, stop and resolve repo root; do not retry relative cd commands.")
    output.append("")
    output.append("Task queue dirs:")
    output.append("- task queue dirs: task briefs live at harness-engine/.dev-harness/task-briefs/")
    output.append("- execution receipts live at harness-engine/.dev-harness/execution-receipts/")
    output.append("- reviews live at harness-engine/.dev-harness/reviews/")
    output.append("- automation state/logs live under harness-engine/.dev-harness/automation/ only; do not use harness-engine/.dev-harness/automation/task-briefs/")
    output.append("- automation state/logs live under harness-engine/.dev-harness/automation/ only; do not use harness-engine/.dev-harness/automation/execution-receipts/")
    output.append("- Prefer the exact absolute TaskBriefPath from automation state when supplied; otherwise locate files under the canonical dirs above before Read.")
    output.append("")
    output.append("Blocked-task rule:")
    output.append("- BLOCKED receipts must include an evaluator/checker repair proposal that would catch the blocker earlier next time.")
    output.append("")

    task_root = harness_root / "task-briefs"
    fetch_count = max(args.RecentTasks * 3, args.RecentTasks)
    task_files = get_recent_files(task_root, fetch_count)
    tasks = [read_task_summary(f) for f in task_files]
    if args.TaskStream:
        tasks = [t for t in tasks if t["stream"] == args.TaskStream]
    tasks.sort(key=lambda t: t["number"] if t["number"] else 0, reverse=True)
    tasks = tasks[:args.RecentTasks]

    output.append("Recent task briefs:")
    if not tasks:
        output.append("- none")
    else:
        for task in tasks:
            output.append(f"- {task['name']}: status={task['status']}; stream={task['stream']}; generated={task['generated']}; goal={task['goal']}")
    output.append("")

    unclaimed_files = get_recent_files(task_root, 100) if task_root.exists() else []
    unclaimed = []
    for f in unclaimed_files:
        t = read_task_summary(f)
        if t["status"] == "UNCLAIMED":
            unclaimed.append(t)
        if len(unclaimed) >= 3:
            break
    if args.TaskStream:
        unclaimed = [t for t in unclaimed if t["stream"] == args.TaskStream]

    output.append("Latest unclaimed task candidates:")
    if not unclaimed:
        output.append("- none")
    else:
        for task in unclaimed:
            output.append(f"- {task['name']}: stream={task['stream']}; generated={task['generated']}")
    output.append("")

    repair_like = [
        t for t in tasks
        if re.search(r"(?i)repair|scope-blocker|external-workspace", t["name"])
        or re.search(r"(?i)\.claude|external workspace|scope blocker", t["goal"])
    ]
    if len(repair_like) >= 3:
        output.append("Repair spiral warning:")
        output.append("- Recent latest tasks are repair-heavy. Do not write another .claude/external-workspace repair unless explicitly requested.")
        output.append("- Treat .claude/settings.local.json and .claude/worktrees/agent-* as local environment blockers outside the structure-proof research stream.")
        output.append("- Resume event-collection progress with: microstructure data feasibility -> schema -> 30d pilot backfill -> V4 cross-variable surrogate.")
        output.append("")

    review_root = harness_root / "reviews"
    review_files = get_recent_files(review_root, args.RecentReviews)
    reviews = [read_review_summary(f) for f in review_files]
    output.append("Recent reviews:")
    if not reviews:
        output.append("- none")
    else:
        for review in reviews:
            output.append(f"- {review['name']}: verdict={review['verdict']}; generated={review['generated']}")
    output.append("")

    receipt_root = harness_root / "execution-receipts"
    receipt_files = get_recent_files(receipt_root, args.RecentReceipts)
    output.append("Recent execution receipts:")
    if not receipt_files:
        output.append("- none")
    else:
        for receipt in receipt_files:
            output.append(f"- {receipt.name}")
    output.append("")

    result = subprocess.run(
        ["git", "-C", str(root), "status", "--short"],
        capture_output=True, text=True,
    )
    changed = result.stdout.strip().splitlines() if result.stdout.strip() else []
    output.append("Working tree status:")
    if not changed:
        output.append("- clean")
    else:
        for line in changed[:30]:
            output.append(f"- {line}")
        if len(changed) > 30:
            output.append(f"- ... {len(changed) - 30} more")
    output.append("")

    output.append("Token rules:")
    output.append("- Do not read every file under task-briefs/ or reviews/.")
    output.append("- Do not guess task or receipt paths under automation/; automation/ is for state and logs, not task queues.")
    output.append("- Read only the selected latest task, its same-number receipt/review, and at most the latest same-stream predecessor unless a gate demands more.")
    output.append("- Do not use patterns like harness-engine/.dev-harness/**/*.md for orientation.")
    output.append("- Do not encode long JSON or many repeated list options in a shell command; use new_task_brief.py --SpecFile instead.")
    output.append("- Do not call new_review_draft.py with a bare path guess such as 081; use --Task <NNN> or --TaskBrief <full-path>.")
    output.append("- Use generators for predictable Markdown; only fill judgement fields by hand.")
    output.append("- If a task is BLOCKED, do not stop at blocker evidence; add the evaluator/checker repair proposal to the receipt.")

    print("\n".join(output))


if __name__ == "__main__":
    main()
